In [21]:
import numpy as np

## 1. DataTypes & Attributes

In [22]:
# NumPy's main datatype is ndarray
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [23]:
type(a1)

numpy.ndarray

In [24]:
a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])

a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
               [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])

In [25]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [26]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [27]:
a1.shape

(3,)

In [28]:
a2.shape

(2, 3)

In [29]:
a3.shape

(2, 3, 3)

In [30]:
a1

array([1, 2, 3])

In [31]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [32]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [33]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [34]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [35]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [36]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [37]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [38]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [39]:
# Create a DataFrame from a NumPy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## 2. Creating arrays

In [40]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [41]:
sample_array.dtype

dtype('int64')

In [45]:
ones = np.ones((2,3) , dtype = "int64")
ones

array([[1, 1, 1],
       [1, 1, 1]])

In [46]:
ones.dtype

dtype('int64')

In [47]:
type(ones)

numpy.ndarray

In [48]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [49]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [53]:
random_array = np.random.randint(0,10, size=(3,5))
random_array

array([[5, 1, 8, 0, 5],
       [6, 1, 2, 8, 2],
       [1, 6, 3, 7, 5]])

In [55]:
random_array.size

15

In [56]:
random_array.shape

(3, 5)

In [58]:
random_array_2 = np.random.random((5,3))
random_array_2

array([[0.7766631 , 0.78316774, 0.83824459],
       [0.86818003, 0.18955539, 0.08893479],
       [0.83155308, 0.43363479, 0.47522655],
       [0.88025012, 0.60261178, 0.94529506],
       [0.08258929, 0.196238  , 0.98987323]])

In [59]:
random_array_2.shape

(5, 3)

In [60]:
random_array_3 = np.random.rand(5,3)
random_array_3

array([[0.46155035, 0.30943147, 0.79539929],
       [0.68528971, 0.50478186, 0.41987923],
       [0.97933161, 0.58316879, 0.56090221],
       [0.62875216, 0.56845512, 0.55111929],
       [0.92433289, 0.01339069, 0.02454155]])

In [64]:
# Pseudo-random numbers
np.random.seed(seed = 0) # random yazılanın aynı kalmasını sağlar. seed = numara farketmez bir kimlik adı gibidir sadece.
random_array_4 = np.random.randint(10, size=(5,3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [ ]:
random_array_5=np.random.random(5,3)
random_array_5