In [21]:
import numpy as np

## 1. DataTypes & Attributes

In [22]:
# NumPy's main datatype is ndarray
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [23]:
type(a1)

numpy.ndarray

In [24]:
a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])

a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
               [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])

In [25]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [26]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [27]:
a1.shape

(3,)

In [28]:
a2.shape

(2, 3)

In [29]:
a3.shape

(2, 3, 3)

In [30]:
a1

array([1, 2, 3])

In [31]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [32]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [33]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [34]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [35]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [36]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [37]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [38]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [39]:
# Create a DataFrame from a NumPy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## 2. Creating arrays

In [40]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [41]:
sample_array.dtype

dtype('int64')

In [45]:
ones = np.ones((2,3) , dtype = "int64")
ones

array([[1, 1, 1],
       [1, 1, 1]])

In [46]:
ones.dtype

dtype('int64')

In [47]:
type(ones)

numpy.ndarray

In [48]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [49]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [53]:
random_array = np.random.randint(0,10, size=(3,5))
random_array

array([[5, 1, 8, 0, 5],
       [6, 1, 2, 8, 2],
       [1, 6, 3, 7, 5]])

In [55]:
random_array.size

15

In [56]:
random_array.shape

(3, 5)

In [58]:
random_array_2 = np.random.random((5,3))
random_array_2

array([[0.7766631 , 0.78316774, 0.83824459],
       [0.86818003, 0.18955539, 0.08893479],
       [0.83155308, 0.43363479, 0.47522655],
       [0.88025012, 0.60261178, 0.94529506],
       [0.08258929, 0.196238  , 0.98987323]])

In [59]:
random_array_2.shape

(5, 3)

In [60]:
random_array_3 = np.random.rand(5,3)
random_array_3

array([[0.46155035, 0.30943147, 0.79539929],
       [0.68528971, 0.50478186, 0.41987923],
       [0.97933161, 0.58316879, 0.56090221],
       [0.62875216, 0.56845512, 0.55111929],
       [0.92433289, 0.01339069, 0.02454155]])

In [64]:
# Pseudo-random numbers
np.random.seed(seed = 0) # random yazılanın aynı kalmasını sağlar. seed = numara farketmez bir kimlik adı gibidir sadece.
random_array_4 = np.random.randint(10, size=(5,3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [66]:
random_array_5=np.random.random((5,3))
random_array_5

array([[0.79172504, 0.52889492, 0.56804456],
       [0.92559664, 0.07103606, 0.0871293 ],
       [0.0202184 , 0.83261985, 0.77815675],
       [0.87001215, 0.97861834, 0.79915856],
       [0.46147936, 0.78052918, 0.11827443]])

## 3.Viewing arrays and matrices

In [67]:
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
a1

array([1, 2, 3])

In [69]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [70]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [71]:
a1[0]

1

In [73]:
a2.shape

(2, 3)

In [72]:
a2[0]

array([1. , 2. , 3.3])

In [74]:
a3.shape

(2, 3, 3)

In [75]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [76]:
a2[1]

array([4. , 5. , 6.5])

In [77]:
a3[:2,:2,:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [79]:
a4 = np.random.randint(10, size=(2,3,4,5))
a4

array([[[[9, 0, 9, 6, 5],
         [3, 1, 8, 0, 4],
         [9, 6, 5, 7, 8],
         [8, 9, 2, 8, 6]],

        [[6, 9, 1, 6, 8],
         [8, 3, 2, 3, 6],
         [3, 6, 5, 7, 0],
         [8, 4, 6, 5, 8]],

        [[2, 3, 9, 7, 5],
         [3, 4, 5, 3, 3],
         [7, 9, 9, 9, 7],
         [3, 2, 3, 9, 7]]],


       [[[7, 5, 1, 2, 2],
         [8, 1, 5, 8, 4],
         [0, 2, 5, 5, 0],
         [8, 1, 1, 0, 3]],

        [[8, 8, 4, 4, 0],
         [9, 3, 7, 3, 2],
         [1, 1, 2, 1, 4],
         [2, 5, 5, 5, 2]],

        [[5, 7, 7, 6, 1],
         [6, 7, 2, 3, 1],
         [9, 5, 9, 9, 2],
         [0, 9, 1, 9, 0]]]])

In [81]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [88]:
a4[:,:,:,:2]

array([[[[9, 0],
         [3, 1]],

        [[6, 9],
         [8, 3]]],


       [[[7, 5],
         [8, 1]],

        [[8, 8],
         [9, 3]]]])

## 4.Manipulating and comparing arrays



In [90]:
a1

array([1, 2, 3])

In [91]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [93]:
a1 + ones

array([2., 3., 4.])

In [94]:
a1 - ones

array([0., 1., 2.])

In [95]:
a1 * ones

array([1., 2., 3.])

In [96]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [97]:
a1 * a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [98]:
a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [99]:
a1 / ones

array([1., 2., 3.])

In [101]:
# Floor division removes the decimals (rounds down)
a2 // a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [102]:
a2 **2

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [103]:
np.square(a2)

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [104]:
a1 % 2

array([1, 0, 1])

In [106]:
a1 / 2

array([0.5, 1. , 1.5])

In [107]:
np.exp(a2)

array([[  2.71828183,   7.3890561 ,  27.11263892],
       [ 54.59815003, 148.4131591 , 665.14163304]])

In [108]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

### Aggregation
Aggregation = performing the same operation on a number of things

In [110]:
listy_list = [1,2,3]
type(listy_list)

list

In [111]:
sum(listy_list)

6

In [112]:
sum(a1)

6

In [113]:
np.sum(a1)

6

# Use Python's methods ("sum()") on Python datatypes and use NumPy's methods on Numpy array (np.sum())

In [115]:
# Create a massive Numpy array
massive_array = np.random.random(100000)
massive_array[:100]

array([0.40081339, 0.9283319 , 0.50417904, 0.61417789, 0.52448713,
       0.7565816 , 0.13843673, 0.4703947 , 0.71330619, 0.8372856 ,
       0.00495611, 0.29233636, 0.58258797, 0.77091718, 0.87636989,
       0.72011788, 0.56772488, 0.39280454, 0.45336131, 0.82291687,
       0.59416932, 0.66840164, 0.80687089, 0.2898391 , 0.02975298,
       0.04936568, 0.83535582, 0.438841  , 0.57457634, 0.19921624,
       0.16466691, 0.16130836, 0.0039912 , 0.89840508, 0.34486382,
       0.74635132, 0.44772775, 0.89349213, 0.65112679, 0.12954539,
       0.96642218, 0.31838338, 0.67196883, 0.31724311, 0.98328964,
       0.82931282, 0.98022729, 0.20208123, 0.02280128, 0.0540468 ,
       0.28335266, 0.6742351 , 0.63960552, 0.32378148, 0.64389754,
       0.18334675, 0.18894126, 0.1859126 , 0.65671056, 0.04619239,
       0.87818728, 0.373481  , 0.30350368, 0.03611455, 0.02423069,
       0.09122017, 0.08091936, 0.66249122, 0.08001905, 0.34557956,
       0.06358647, 0.23513018, 0.83936412, 0.11803496, 0.34342