In [21]:
import numpy as np

## 1. DataTypes & Attributes

In [22]:
# NumPy's main datatype is ndarray
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [23]:
type(a1)

numpy.ndarray

In [24]:
a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])

a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
               [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])

In [25]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [26]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [27]:
a1.shape

(3,)

In [28]:
a2.shape

(2, 3)

In [29]:
a3.shape

(2, 3, 3)

In [30]:
a1

array([1, 2, 3])

In [31]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [32]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [33]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [34]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [35]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [36]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [37]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [38]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [39]:
# Create a DataFrame from a NumPy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## 2. Creating arrays

In [40]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [41]:
sample_array.dtype

dtype('int64')

In [45]:
ones = np.ones((2,3) , dtype = "int64")
ones

array([[1, 1, 1],
       [1, 1, 1]])

In [46]:
ones.dtype

dtype('int64')

In [47]:
type(ones)

numpy.ndarray

In [48]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [49]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [51]:
random_array = np.random.randint()

TypeError: randint() takes at least 1 positional argument (0 given)